"use client";

import { useState } from "react";

type Question = {
  id: string;
  question: string;
  recommendation: string;
};

const questions: Question[] = [
  {
    id: "ai-tools",
    question: "Have you used AI tools such as ChatGPT, Copilot, or Gemini before?",
    recommendation:
      "Learn the basic capabilities and limitations of common AI tools. Experiment with simple tasks while remembering that AI output still requires human judgment.",
  },
  {
    id: "verification",
    question: "Do you verify important information generated by AI?",
    recommendation:
      "Verify important AI-generated claims using reliable and independent sources, especially before using them for school, work, health, financial, or other important decisions.",
  },
  {
    id: "deepfakes",
    question: "Do you know what a deepfake is?",
    recommendation:
      "Learn how generative AI can create convincing fake images, videos, and audio. Look for context, source credibility, and independent confirmation before trusting suspicious media.",
  },
  {
    id: "hallucinations",
    question: "Do you know that AI can give wrong or made-up answers?",
    recommendation:
      "Treat AI responses as information to evaluate rather than guaranteed facts. AI systems can produce inaccurate or completely invented information while sounding confident.",
  },
  {
    id: "bias",
    question: "Do you understand that AI systems can have bias?",
    recommendation:
      "Learn how training data, system design, and human decisions can introduce bias into AI systems and affect fairness, representation, and automated decisions.",
  },
];

export default function AILiteracyAssessment() {
  const [answers, setAnswers] = useState<Record<string, boolean>>({});

  const handleAnswer = (id: string, value: boolean) => {
    setAnswers((currentAnswers) => ({
      ...currentAnswers,
      [id]: value,
    }));
  };

  const answeredCount = Object.keys(answers).length;
  const completed = answeredCount === questions.length;

  const yesCount = Object.values(answers).filter(Boolean).length;
  const score = Math.round((yesCount / questions.length) * 100);

  const recommendations = questions.filter(
    (question) => answers[question.id] === false,
  );

  const understoodAreas = questions.filter(
    (question) => answers[question.id] === true,
  );

  let level = "Not completed";
  let resultExplanation =
    "Answer all five questions to receive your AI literacy result.";

  if (completed) {
    if (score >= 80) {
      level = "Advanced";
      resultExplanation =
        "Your answers show strong awareness of several important AI literacy concepts, including verification, AI errors, deepfakes, and bias. Continue developing these skills as AI systems and their uses change.";
    } else if (score >= 50) {
      level = "Intermediate";
      resultExplanation =
        "You understand several important ideas about artificial intelligence, but there are still knowledge gaps that could affect how critically and responsibly you use or evaluate AI-generated information. Focus on the areas identified below.";
    } else {
      level = "Beginner";
      resultExplanation =
        "You are still developing your understanding of important AI concepts. Building knowledge about verification, AI-generated misinformation, hallucinations, bias, and responsible use will help you make safer and more informed decisions when interacting with AI.";
    }
  }

  return (
    <section className="mx-auto max-w-3xl rounded-2xl border bg-white p-6 shadow-sm">
      <h2 className="text-2xl font-bold text-blue-900">
        AI Literacy Assessment
      </h2>

      <p className="mt-3 text-gray-600">
        Answer these questions to review your understanding of AI tools, their
        limitations, and some of the skills needed to use AI critically and
        responsibly.
      </p>

      <div className="mt-8 space-y-6">
        {questions.map((item) => (
          <fieldset key={item.id} className="rounded-xl border p-4">
            <legend className="px-1 font-semibold text-gray-800">
              {item.question}
            </legend>

            <div className="mt-4 flex gap-3">
              <button
                type="button"
                aria-pressed={answers[item.id] === true}
                onClick={() => handleAnswer(item.id, true)}
                className={`rounded-lg px-4 py-2 font-semibold focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-cyan-600 focus-visible:ring-offset-2 ${
                  answers[item.id] === true
                    ? "bg-cyan-600 text-white"
                    : "bg-gray-100 text-gray-800"
                }`}
              >
                Yes
              </button>

              <button
                type="button"
                aria-pressed={answers[item.id] === false}
                onClick={() => handleAnswer(item.id, false)}
                className={`rounded-lg px-4 py-2 font-semibold focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-cyan-600 focus-visible:ring-offset-2 ${
                  answers[item.id] === false
                    ? "bg-cyan-600 text-white"
                    : "bg-gray-100 text-gray-800"
                }`}
              >
                No
              </button>
            </div>
          </fieldset>
        ))}
      </div>

      <div
        className="mt-8 rounded-xl bg-gray-50 p-5"
        aria-live="polite"
        aria-atomic="true"
      >
        <h3 className="text-xl font-bold text-blue-900">Your Result</h3>

        {!completed ? (
          <p className="mt-3 text-gray-700">
            You have answered {answeredCount} of {questions.length} questions.
            Complete the assessment to receive your score and recommendations.
          </p>
        ) : (
          <>
            <p className="mt-3 text-lg font-semibold">Score: {score}/100</p>

            <p className="mt-2 font-semibold">AI Literacy Level: {level}</p>

            <p className="mt-3 leading-7 text-gray-700">
              {resultExplanation}
            </p>
          </>
        )}
      </div>

      {completed && understoodAreas.length > 0 && (
        <div className="mt-6 rounded-xl border p-5">
          <h3 className="text-xl font-bold text-blue-900">
            What You Already Understand
          </h3>

          <p className="mt-3 text-gray-700">
            You reported familiarity with {understoodAreas.length} of the{" "}
            {questions.length} AI literacy areas covered by this assessment.
            Keep strengthening this knowledge as AI technologies continue to
            develop.
          </p>
        </div>
      )}

      {completed && recommendations.length > 0 && (
        <div className="mt-6 rounded-xl border p-5">
          <h3 className="text-xl font-bold text-blue-900">
            Recommended Learning
          </h3>

          <p className="mt-3 text-gray-700">
            Focus on the areas where you answered no. These topics can help you
            evaluate AI systems and AI-generated information more critically.
          </p>

          <ul className="mt-4 list-disc space-y-3 pl-5 text-gray-700">
            {recommendations.map((item) => (
              <li key={item.id}>{item.recommendation}</li>
            ))}
          </ul>
        </div>
      )}

      {completed && recommendations.length === 0 && (
        <div className="mt-6 rounded-xl border p-5">
          <h3 className="text-xl font-bold text-blue-900">
            Strong AI Literacy Foundation
          </h3>

          <p className="mt-3 leading-7 text-gray-700">
            You reported understanding all five areas covered in this
            assessment. Continue questioning AI output, checking important
            information, learning about emerging AI risks, and using human
            judgment when making decisions.
          </p>
        </div>
      )}

      <p className="mt-6 text-sm leading-6 text-gray-500">
        This assessment is an educational self-check rather than a formal
        measure of AI expertise. AI literacy also includes practical experience,
        critical thinking, responsible use, and continued learning as the
        technology evolves.
      </p>
    </section>
  );
}