"use client";

import { useState } from "react";

type Question = {
  id: string;
  question: string;
  recommendation: string;
};

const questions: Question[] = [
  {
    id: "ai-tools",
    question: "Have you used AI tools such as ChatGPT, Copilot, or Gemini before?",
    recommendation: "Try learning the basic uses and limits of common AI tools.",
  },
  {
    id: "verification",
    question: "Do you verify important information generated by AI?",
    recommendation: "Always check important AI-generated information using reliable sources.",
  },
  {
    id: "deepfakes",
    question: "Do you know what a deepfake is?",
    recommendation: "Learn how AI can create realistic fake images, videos, and audio.",
  },
  {
    id: "hallucinations",
    question: "Do you know that AI can give wrong or made-up answers?",
    recommendation: "Remember that AI can make mistakes, even when it sounds confident.",
  },
  {
    id: "bias",
    question: "Do you understand that AI systems can have bias?",
    recommendation: "Learn how AI bias can affect decisions, fairness, and trust.",
  },
];

export default function AILiteracyAssessment() {
  const [answers, setAnswers] = useState<Record<string, boolean>>({});

  const handleAnswer = (id: string, value: boolean) => {
    setAnswers((currentAnswers) => ({
      ...currentAnswers,
      [id]: value,
    }));
  };

  const answeredCount = Object.keys(answers).length;
  const yesCount = Object.values(answers).filter(Boolean).length;
  const score = Math.round((yesCount / questions.length) * 100);

  let level = "Not completed";
  let message = "Answer all questions to get your AI literacy score.";

  if (answeredCount === questions.length) {
    if (score >= 80) {
      level = "Advanced";
      message =
        "You have strong AI awareness. Keep learning and verifying information.";
    } else if (score >= 50) {
      level = "Intermediate";
      message =
        "You understand some AI concepts, but there are important areas to improve.";
    } else {
      level = "Beginner";
      message =
        "Start with the basics of AI, deepfakes, bias, and verification.";
    }
  }

  const recommendations = questions.filter(
    (question) => answers[question.id] === false
  );

  return (
    <section className="mx-auto max-w-3xl rounded-2xl border bg-white p-6 shadow-sm">
      <h2 className="text-2xl font-bold text-blue-900">
        AI Literacy Assessment
      </h2>

      <p className="mt-3 text-gray-600">
        Answer these simple questions to check your understanding of AI tools,
        risks, and responsible use.
      </p>

      <div className="mt-8 space-y-6">
        {questions.map((item) => (
          <div key={item.id} className="rounded-xl border p-4">
            <p className="font-semibold text-gray-800">{item.question}</p>

            <div className="mt-4 flex gap-3">
              <button
                type="button"
                onClick={() => handleAnswer(item.id, true)}
                className={`rounded-lg px-4 py-2 font-semibold ${
                  answers[item.id] === true
                    ? "bg-cyan-600 text-white"
                    : "bg-gray-100 text-gray-800"
                }`}
              >
                Yes
              </button>

              <button
                type="button"
                onClick={() => handleAnswer(item.id, false)}
                className={`rounded-lg px-4 py-2 font-semibold ${
                  answers[item.id] === false
                    ? "bg-cyan-600 text-white"
                    : "bg-gray-100 text-gray-800"
                }`}
              >
                No
              </button>
            </div>
          </div>
        ))}
      </div>

      <div className="mt-8 rounded-xl bg-gray-50 p-5">
        <h3 className="text-xl font-bold text-blue-900">Your Result</h3>

        <p className="mt-3 text-lg font-semibold">Score: {score}/100</p>

        <p className="mt-2 font-semibold">Level: {level}</p>

        <p className="mt-2 text-gray-700">{message}</p>
      </div>

      {answeredCount === questions.length && recommendations.length > 0 && (
        <div className="mt-6 rounded-xl border p-5">
          <h3 className="text-xl font-bold text-blue-900">
            Recommended Learning
          </h3>

          <ul className="mt-4 list-disc space-y-2 pl-5 text-gray-700">
            {recommendations.map((item) => (
              <li key={item.id}>{item.recommendation}</li>
            ))}
          </ul>
        </div>
      )}
    </section>
  );
}