"use client";

import { useState } from "react";

type Question = {
  id: string;
  question: string;
  recommendation: string;
};

const questions: Question[] = [
  {
    id: "ai-tools",
    question: "Have you used AI tools such as ChatGPT, Copilot, or Gemini before?",
    recommendation: "Try learning the basic uses and limits of common AI tools.",
  },
  {
    id: "verification",
    question: "Do you verify important information generated by AI?",
    recommendation:
      "Always check important AI-generated information using reliable sources.",
  },
  {
    id: "deepfakes",
    question: "Do you know what a deepfake is?",
    recommendation:
      "Learn how AI can create realistic fake images, videos, and audio.",
  },
  {
    id: "hallucinations",
    question: "Do you know that AI can give wrong or made-up answers?",
    recommendation:
      "Remember that AI can make mistakes, even when it sounds confident.",
  },
  {
    id: "bias",
    question: "Do you understand that AI systems can have bias?",
    recommendation:
      "Learn how AI bias can affect decisions, fairness, and trust.",
  },
];

export default function AILiteracyAssessmentClient() {
  const [answers, setAnswers] = useState<Record<string, boolean>>({});

  function handleAnswer(id: string, value: boolean) {
    setAnswers((currentAnswers) => ({
      ...currentAnswers,
      [id]: value,
    }));
  }

  const answeredCount = Object.keys(answers).length;
  const yesCount = Object.values(answers).filter(Boolean).length;
  const completed = answeredCount === questions.length;
  const score = Math.round((yesCount / questions.length) * 100);

  let level = "Not completed";
  let message = "Answer all questions to get your AI literacy score.";

  if (completed) {
    if (score >= 80) {
      level = "Advanced";
      message =
        "You have strong AI awareness. Keep learning and verifying information.";
    } else if (score >= 50) {
      level = "Intermediate";
      message =
        "You understand some AI concepts, but there are important areas to improve.";
    } else {
      level = "Beginner";
      message =
        "Start with the basics of AI, deepfakes, bias, and verification.";
    }
  }

  const recommendations = questions.filter(
    (question) => answers[question.id] === false,
  );

  return (
    <section
      className="mx-auto max-w-3xl rounded-2xl border border-gray-200 bg-white p-6 shadow-sm transition-colors dark:border-slate-700 dark:bg-slate-800"
      aria-labelledby="ai-literacy-assessment-title"
    >
      <h1
        id="ai-literacy-assessment-title"
        className="text-3xl font-bold text-blue-900 transition-colors dark:text-blue-200"
      >
        AI Literacy Assessment
      </h1>

      <p className="mt-3 text-gray-600 transition-colors dark:text-slate-300">
        Answer these simple questions to check your understanding of AI tools,
        risks, and responsible use.
      </p>

      <div className="mt-8 space-y-6">
        {questions.map((item) => (
          <fieldset
            key={item.id}
            className="rounded-xl border border-gray-200 p-4 transition-colors dark:border-slate-600 dark:bg-slate-900/40"
          >
            <legend className="font-semibold text-gray-800 transition-colors dark:text-slate-200">
              {item.question}
            </legend>

            <div className="mt-4 flex gap-3">
              <button
                type="button"
                aria-pressed={answers[item.id] === true}
                onClick={() => handleAnswer(item.id, true)}
                className={`rounded-lg px-4 py-2 font-semibold transition-colors focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-cyan-600 dark:focus-visible:outline-cyan-400 ${
                  answers[item.id] === true
                    ? "bg-cyan-700 text-white dark:bg-cyan-600"
                    : "bg-gray-100 text-gray-800 hover:bg-gray-200 dark:bg-slate-700 dark:text-slate-200 dark:hover:bg-slate-600"
                }`}
              >
                Yes
              </button>

              <button
                type="button"
                aria-pressed={answers[item.id] === false}
                onClick={() => handleAnswer(item.id, false)}
                className={`rounded-lg px-4 py-2 font-semibold transition-colors focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-cyan-600 dark:focus-visible:outline-cyan-400 ${
                  answers[item.id] === false
                    ? "bg-cyan-700 text-white dark:bg-cyan-600"
                    : "bg-gray-100 text-gray-800 hover:bg-gray-200 dark:bg-slate-700 dark:text-slate-200 dark:hover:bg-slate-600"
                }`}
              >
                No
              </button>
            </div>
          </fieldset>
        ))}
      </div>

      <div
        className="mt-8 rounded-xl border border-gray-200 bg-gray-50 p-5 transition-colors dark:border-slate-700 dark:bg-slate-900"
        aria-live="polite"
        aria-atomic="true"
      >
        <h2 className="text-xl font-bold text-blue-900 transition-colors dark:text-blue-200">
          Your Result
        </h2>

        <p className="mt-3 text-lg font-semibold text-gray-900 dark:text-slate-100">
          Score: {score}/100
        </p>

        <p className="mt-2 font-semibold text-gray-900 dark:text-slate-100">
          Level: {level}
        </p>

        <p className="mt-2 text-gray-700 transition-colors dark:text-slate-300">
          {message}
        </p>
      </div>

      {completed && recommendations.length > 0 && (
        <div className="mt-6 rounded-xl border border-gray-200 bg-white p-5 transition-colors dark:border-slate-700 dark:bg-slate-900">
          <h2 className="text-xl font-bold text-blue-900 transition-colors dark:text-blue-200">
            Recommended Learning
          </h2>

          <ul className="mt-4 list-disc space-y-2 pl-5 text-gray-700 transition-colors dark:text-slate-300">
            {recommendations.map((item) => (
              <li key={item.id}>{item.recommendation}</li>
            ))}
          </ul>
        </div>
      )}

      {completed && recommendations.length === 0 && (
        <div className="mt-6 rounded-xl border border-gray-200 bg-white p-5 transition-colors dark:border-slate-700 dark:bg-slate-900">
          <h2 className="text-xl font-bold text-blue-900 transition-colors dark:text-blue-200">
            Strong AI Literacy
          </h2>

          <p className="mt-3 text-gray-700 transition-colors dark:text-slate-300">
            You answered yes to all questions. Keep reviewing new AI risks,
            capabilities, and responsible-use practices as the technology
            changes.
          </p>
        </div>
      )}
    </section>
  );
}